# name: daily-build

# on:
#   workflow_dispatch:

# jobs:
#   daily-build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [20.x]

#     steps:
#       - name: 'Setup ENV'
#         run: |
#           DATE=`date "+%Y%m%d"`
#           run_number=$(($GITHUB_RUN_NUMBER % 100))
#           run_number=$(printf "%02d" $run_number)
#           build_number="${DATE}${run_number}"
#           echo '$build_number='$build_number
#           echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
